config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  resources :users, only: [:show]
  resources :commits, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github_user.rb
class GithubUser
  attr_reader :username,
              :followers,
              :following,
              :avatar,
              :bio

  def initialize(raw_user)
    @username  = raw_user[:login]
    @followers = raw_user[:followers]
    @following = raw_user[:following]
    @avatar    = raw_user[:avatar_url]
    @bio       = raw_user[:bio]
  end

  def self.find(token)
    raw_user = GithubService.find_by_token(token)
    GithubUser.new(raw_user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid         = auth_info.uid
      new_user.username    = auth_info.info.nickname
      new_user.oauth_token = auth_info.credentials.token
    end
  end
end

app/models/user_activity.rb
class UserActivity
  attr_reader :repos,
              :commits

  def initialize(events)
    @repos   = parse_repos(events)
    @commits = parse_commits(events)
  end

  def self.events(username, token)
    raw_events = GithubService.user_events(username, token)
    UserActivity.new(raw_events)
  end

  def parse_repos(events)
    push_events = parse_commit_events(events)
    push_events.map { |event| event[:repo] }
  end

  def parse_commits(events)
    push_events = parse_commit_events(events)
    push_events.map { |event| event[:payload][:commits] }.flatten
  end

  def parse_commit_events(events)
    events.map { |event| event if event[:type] == "PushEvent" }.compact
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  def index
    @user_events = UserActivity.events(current_user.username, current_user.oauth_token)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to user_path(user)
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @github_user = GithubUser.find(current_user.oauth_token)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/commits/index.html.erb
<div class="container">
  <div class="well">
    <h2>Recent Commit Activity</h2>
    <ul>
      <% @user_events.commits.each do |commit| %>
        <li>
          <%= link_to commit[:message], commit[:url] %> 
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<div class="container text-center">
  <h1>Welcome to your Github Clone!</h1>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button class="navbar-toggle" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Github Wrapper</a>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-left">
      <li>
        <a href="#">Repos</a>
      </li>
      <li>
        <a href="#">Starred Items</a>
      </li>
      <% if current_user %>
        <li>
          <%= link_to "Profile", user_path(current_user) %>
        </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li>
          Hello, <%= current_user.username %>
        </li>
        <li>
          <%= link_to "Logout", logout_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign in with Github", github_login_path %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApicuriousGithub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'  %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="container">
  <div class="well text-center">
    <% if current_user %>
      <div class="row">
        <div class="col-md-12">
          <%= image_tag(@github_user.avatar, class: "img-circle", height: '300', width: '300') %>
          <div class="row">
            <div class="col-md-12 text-center">
              <h2><%= @github_user.username %></h2>
              Bio: <%= @github_user.bio %>
            </div>
          </div>
        </div>
        <div class="col-md-12">
          Following: <%= @github_user.following %>
          Followers: <%= @github_user.followers %>
          <div class="row">
            <div class="col-md-12">
              <%= link_to "View Recent Commits", commits_path %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>